/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GetCountGUI;

import Controller.BatchController;
import Controller.FieldController;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JOptionPane;

/**
 *
 * @author Rangika
 */
public class GetCount extends javax.swing.JFrame {

    private String academicYear;
    private int batchNo=0;
    private String field;
    private String batchID;
    private String fieldID;
    public GetCount() {
        initComponents();
        jField.requestFocus();
    }
    
    public void setCursor(int[] i,JComponent[] j,KeyEvent e){                   // Set the cursour when neccessary keys are pressed
        for(int x=0;x<i.length;x++){
            if(e.getKeyCode()==i[x]){
                j[x].requestFocus();
            }
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        batch = new javax.swing.ButtonGroup();
        jPanelGetCounts = new javax.swing.JPanel();
        jField = new javax.swing.JComboBox();
        jLabelField = new javax.swing.JLabel();
        jLabelYear = new javax.swing.JLabel();
        jSearch = new javax.swing.JButton();
        jYear = new javax.swing.JTextField();
        jLabelBatch = new javax.swing.JLabel();
        jBatch1 = new javax.swing.JRadioButton();
        jBatch2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Selection");
        setResizable(false);

        jPanelGetCounts.setBackground(new java.awt.Color(255, 255, 255));

        jField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Power", "Ref & Air", "Electronic", "Mechanist", "Welders", "Wood work", "Plumbers", "Construction Supervisor", "ICT", "Computer Graphic Designing" }));
        jField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFieldActionPerformed(evt);
            }
        });
        jField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFieldKeyPressed(evt);
            }
        });

        jLabelField.setText("Field :");

        jLabelYear.setText("Academic Year :");

        jSearch.setText("Search");
        jSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchActionPerformed(evt);
            }
        });
        jSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSearchKeyPressed(evt);
            }
        });

        jYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jYearKeyPressed(evt);
            }
        });

        jLabelBatch.setText("Batch :");

        batch.add(jBatch1);
        jBatch1.setText("1");
        jBatch1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBatch1KeyPressed(evt);
            }
        });

        batch.add(jBatch2);
        jBatch2.setText("2");
        jBatch2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBatch2KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelGetCountsLayout = new javax.swing.GroupLayout(jPanelGetCounts);
        jPanelGetCounts.setLayout(jPanelGetCountsLayout);
        jPanelGetCountsLayout.setHorizontalGroup(
            jPanelGetCountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGetCountsLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanelGetCountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelBatch)
                    .addComponent(jLabelYear)
                    .addComponent(jLabelField))
                .addGap(47, 47, 47)
                .addGroup(jPanelGetCountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jYear, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelGetCountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelGetCountsLayout.createSequentialGroup()
                            .addComponent(jBatch1)
                            .addGap(72, 72, 72)
                            .addComponent(jBatch2))
                        .addComponent(jField, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(238, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGetCountsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );
        jPanelGetCountsLayout.setVerticalGroup(
            jPanelGetCountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGetCountsLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanelGetCountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelField)
                    .addComponent(jField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanelGetCountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelYear)
                    .addComponent(jYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanelGetCountsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBatch)
                    .addComponent(jBatch1)
                    .addComponent(jBatch2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jSearch)
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelGetCounts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelGetCounts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFieldActionPerformed

    private void jFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFieldKeyPressed
        int[] i ={10};
        JComponent[] j ={jYear};
        setCursor(i,j, evt);
    }//GEN-LAST:event_jFieldKeyPressed

    private void jYearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jYearKeyPressed
        int[] i ={38,40};
        JComponent[] j ={jField,jBatch1};
        setCursor(i,j, evt);
    }//GEN-LAST:event_jYearKeyPressed

    private void jBatch1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBatch1KeyPressed
        int[] i ={38,39,40};
        JComponent[] j ={jYear,jBatch2,jSearch};
        setCursor(i,j, evt);
        if(evt.getKeyCode()==39){
            jBatch2.setSelected(true);
            batchNo=2;
        }
        if(evt.getKeyCode()==10){
            jBatch1.setSelected(true);
            batchNo=1;
        }
    }//GEN-LAST:event_jBatch1KeyPressed

    private void jBatch2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBatch2KeyPressed
        int[] i ={38,37,40};
        JComponent[] j ={jYear,jBatch1,jSearch};
        setCursor(i,j, evt);
        if(evt.getKeyCode()==37){
            jBatch1.setSelected(true);
            batchNo=1;
        }
        if(evt.getKeyCode()==10){
            jBatch2.setSelected(true);
            batchNo=2;
        }
    }//GEN-LAST:event_jBatch2KeyPressed

    private void jSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSearchKeyPressed
        int[] i ={38};
        JComponent[] j ={jBatch1};
        setCursor(i,j, evt);
        
        
    }//GEN-LAST:event_jSearchKeyPressed

    private void jSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchActionPerformed
        academicYear=jYear.getText();
        field=jField.getSelectedItem().toString();
        
        try {
            fieldID=FieldController.getFieldID(field);
            batchID=BatchController.getBatchID(academicYear,batchNo);
        
            String year = String.valueOf(Calendar.getInstance().get(Calendar.YEAR)); 

            if(academicYear.isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "Please enter a year","Error",0);
                jYear.requestFocus();

            } else if(academicYear.length()!=4 | isNumber(academicYear)){
                JOptionPane.showMessageDialog(rootPane, "The year you eneterd is incorrect","Error",0);
                jYear.requestFocus();
            }        
            else if(Integer.parseInt(academicYear)>Integer.parseInt(year)+2){
                JOptionPane.showMessageDialog(rootPane, "The year you eneterd is far future","Error",0);
                jYear.requestFocus();
            }
            else{
                if(field=="All"){
                    
                }else{
                    ShowCount showCount= new ShowCount(batchID,field,fieldID);
                    showCount.setVisible(true);
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GetCount.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GetCount.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }//GEN-LAST:event_jSearchActionPerformed

    private boolean isNumber(String number){
       
        if(!number.matches("\\d+")){
                return true;
        }return false;
      }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GetCount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GetCount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GetCount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GetCount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GetCount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup batch;
    private javax.swing.JRadioButton jBatch1;
    private javax.swing.JRadioButton jBatch2;
    private javax.swing.JComboBox jField;
    private javax.swing.JLabel jLabelBatch;
    private javax.swing.JLabel jLabelField;
    private javax.swing.JLabel jLabelYear;
    private javax.swing.JPanel jPanelGetCounts;
    private javax.swing.JButton jSearch;
    private javax.swing.JTextField jYear;
    // End of variables declaration//GEN-END:variables
}
