/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StudentGUI;

import Model.Institute;
import java.awt.event.KeyEvent;
import javax.swing.JComponent;
import javax.swing.JFrame;

/**
 *
 * @author Hasini
 */
public class StudentDetailSelection extends javax.swing.JFrame {
    Institute ins = Institute.getInstitute();

    /**
     * Creates new form StudentDetailSelection
     */
    public StudentDetailSelection() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        revalidate();
    }
    
    public void setCursor(int[] i,JComponent[] j,KeyEvent e){                   // Set the cursour when neccessary keys are pressed
        for(int x=0;x<i.length;x++){
            if(e.getKeyCode()==i[x]){
                j[x].requestFocus();
            }
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jAcedemicYear = new javax.swing.JTextField();
        jField = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jGenerate = new javax.swing.JButton();
        jOne = new javax.swing.JRadioButton();
        jTwo = new javax.swing.JRadioButton();
        jHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel1.setText("Generate Index Number");

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel2.setText("Year :");
        jLabel2.setToolTipText("Enter the academic year of the student");

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel3.setText("Field  :");

        jAcedemicYear.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jAcedemicYear.setToolTipText("Enter the academic year of student");
        jAcedemicYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAcedemicYearActionPerformed(evt);
            }
        });
        jAcedemicYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jAcedemicYearKeyPressed(evt);
            }
        });

        jField.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "..................", "Electrical", "Ref & Air", "Electronic", "Machinist", "Welder", "Wood Work", "Plumber", "Construction", "ICT", "Graphic" }));
        jField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFieldKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel4.setText("Batch  :");

        jGenerate.setBackground(new java.awt.Color(255, 255, 255));
        jGenerate.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jGenerate.setText("AUTO GENERATE");
        jGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGenerateActionPerformed(evt);
            }
        });

        jOne.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jOne);
        jOne.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jOne.setText("1");
        jOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOneActionPerformed(evt);
            }
        });
        jOne.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jOneKeyPressed(evt);
            }
        });

        jTwo.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jTwo);
        jTwo.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jTwo.setText("2");
        jTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTwoActionPerformed(evt);
            }
        });
        jTwo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTwoKeyPressed(evt);
            }
        });

        jHome.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jHome.setText("HOME");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jOne)
                        .addGap(30, 30, 30)
                        .addComponent(jTwo))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jAcedemicYear, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(175, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addComponent(jHome, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jGenerate)
                .addGap(61, 61, 61))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jAcedemicYear, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jOne)
                        .addComponent(jTwo))
                    .addComponent(jLabel4))
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jGenerate, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(jHome, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAcedemicYearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jAcedemicYearKeyPressed
         int[] i ={40};
        JComponent[] j ={jOne};
        setCursor(i,j, evt);
        jOne.setSelected(true);
    }//GEN-LAST:event_jAcedemicYearKeyPressed

    private void jFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFieldKeyPressed
         int[] i ={10};
        JComponent[] j ={jGenerate};
        setCursor(i,j, evt);
        
    }//GEN-LAST:event_jFieldKeyPressed

    private void jOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jOneActionPerformed
    private int batchNo;
    private void jOneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jOneKeyPressed
        int[] i ={39,40,38};
        JComponent[] j ={jTwo,jField,jAcedemicYear};
        setCursor(i,j, evt);

        if(evt.getKeyCode()==39){
            jTwo.setSelected(true);
            batchNo=2;
        }

    }//GEN-LAST:event_jOneKeyPressed

    private void jTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTwoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTwoActionPerformed

    private void jTwoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTwoKeyPressed
        int[] i ={37,40,38};
        JComponent[] j ={jOne,jField,jAcedemicYear};
        setCursor(i,j, evt);

        if(evt.getKeyCode()==37){
            jOne.setSelected(true);
            batchNo=1;
        }
    }//GEN-LAST:event_jTwoKeyPressed

    private void jAcedemicYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAcedemicYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAcedemicYearActionPerformed

    private void jGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGenerateActionPerformed
        String academicYear = jAcedemicYear.getText();
        String field =jField.getSelectedItem().toString();
        
        ins.addBatch( academicYear, batchNo);
        
        
    }//GEN-LAST:event_jGenerateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDetailSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDetailSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDetailSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDetailSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDetailSelection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField jAcedemicYear;
    private javax.swing.JComboBox jField;
    private javax.swing.JButton jGenerate;
    private javax.swing.JButton jHome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jOne;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jTwo;
    // End of variables declaration//GEN-END:variables
}
