/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DropoutsGUI;

import Controller.EstablishmentController;
import Controller.StudentController;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Rangika
 */
public class MarkDropout extends javax.swing.JFrame {

    /**
     * Creates new form MarkDropout
     */
    private String field;
    private String year;
    private int batchNo;
    private String number;
    private String indexNo;
    private int status;

    public MarkDropout() {
        initComponents();
        //jComboField.requestFocus();
        jBtnDropout.setVisible(false);
    }
    
     public void setCursor(int[] i,JComponent[] j,KeyEvent e){                   // Set the cursour when neccessary keys are pressed
        for(int x=0;x<i.length;x++){
            if(e.getKeyCode()==i[x]){
                j[x].requestFocus();
            }
        }
       
    }
     
    public void setClear(){
        jName.setForeground(Color.black);
        jName.setText(null);
        jIndexNo.setForeground(Color.black);
        jIndexNo.setText(null);
        jEstablishment1.setText(null);
        jBtnDropout.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboField = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jTextYear = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBatchNo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jTextNumber = new javax.swing.JTextField();
        jBtnMarkDropout = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jIndexNo = new javax.swing.JLabel();
        jName = new javax.swing.JLabel();
        jEstablishment1 = new javax.swing.JLabel();
        jBtnDropout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Index no :");

        jComboField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CGD", "CS", "EL", "EN", "ICT", "MM", "MW", "PL", "RA", "WW" }));
        jComboField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboFieldKeyPressed(evt);
            }
        });

        jLabel2.setText("/");

        jTextYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextYearKeyPressed(evt);
            }
        });

        jLabel3.setText("/");

        jComboBatchNo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02" }));
        jComboBatchNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBatchNoKeyPressed(evt);
            }
        });

        jLabel4.setText("/");

        jTextNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextNumberKeyPressed(evt);
            }
        });

        jBtnMarkDropout.setText("Mark Dropout");
        jBtnMarkDropout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMarkDropoutActionPerformed(evt);
            }
        });
        jBtnMarkDropout.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtnMarkDropoutKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextYear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBatchNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(307, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnMarkDropout)
                .addGap(63, 63, 63))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBatchNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jBtnMarkDropout)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setText("Name :");

        jLabel6.setText("Index No :");

        jLabel7.setText("Establishment 1 :");

        jBtnDropout.setText("Dropout");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jEstablishment1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addComponent(jName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jIndexNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnDropout, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jIndexNo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jName, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jEstablishment1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(jBtnDropout)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void getData() throws SQLException, ClassNotFoundException {
        String bNo;
        field = jComboField.getSelectedItem().toString();
        bNo=jComboBatchNo.getSelectedItem().toString();
        batchNo = Integer.parseInt(bNo);
        year = jTextYear.getText();
        number = jTextNumber.getText();
        indexNo = field + "/" + year + "/" + bNo + "/" + number;
        String name=StudentController.searchStudent(indexNo);
        if(StudentController.isExist(indexNo)==false){
            setClear();
            jIndexNo.setText(indexNo);
            jIndexNo.setForeground(Color.red);
            JOptionPane.showMessageDialog(rootPane, "The index number "+indexNo+" does not exist.","Error",0);
            jTextNumber.requestFocus();
        }
        else if(name==null){
            setClear();
            jName.setText("-");
            jName.setForeground(Color.red);
            jEstablishment1.setText("-");
            jEstablishment1.setForeground(Color.red);
            jIndexNo.setText(indexNo);
            jIndexNo.setForeground(Color.red);
            JOptionPane.showMessageDialog(rootPane, "Selected student is already marked as a dropout","Error",0);
            jTextNumber.requestFocus();
        }else{
            setClear();
            jIndexNo.setText(indexNo);
            jName.setForeground(Color.black);
            jEstablishment1.setForeground(Color.blue);
            jIndexNo.setForeground(Color.black);
            jName.setText(name);
            jBtnDropout.setVisible(true);
//            if(EstablishmentController.getEstablishment(indexNo,1)==""){
//                jEstablishment1.setText("-");
//                status=0;
//            }else if(EstablishmentController.getEstablishment(indexNo,1)==null){
//                jEstablishment1.setText("-");
//                status=0;
//            }else{
//                for(int i=1;i<12;i++){
//                    jEstablishment1.setText(EstablishmentController.getEstablishment(indexNo,1));
//                }
//            }
            JLabel[] labels = new JLabel[11];
            for(int i=1;i<12;i++){
                String companyName=EstablishmentController.getEstablishment(indexNo,i);
                if(companyName==""){
                    jEstablishment1.setText("-");
                    status = i-1;
                    System.out.println("bbbbbbbbbb");
                    break;
                } else if (companyName == null) {
                    jEstablishment1.setText("-");
                    status = i-1;
                    labels[i] = new JLabel("Establishment"+i);
                    jPanel1.add(labels[i]);
                    //JLabel ll+i = new JLabel("label 1");
                    //jLabelName = new javax.swing.JLabel();
                    //jLabel1.setText("Establishment"+i);
                    //jPanel1.
                    break;
                } else {
                    //JLabel establishment+"i"=new JLabel();
                }
            }
        }
    }
    
    private void jBtnMarkDropoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMarkDropoutActionPerformed
        try {
            getData();
        } catch (SQLException ex) {
            Logger.getLogger(MarkDropout.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MarkDropout.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnMarkDropoutActionPerformed

    private void jComboFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboFieldKeyPressed
        int[] i ={39};
        JComponent[] j ={jTextYear};
        setCursor(i,j, evt);
    }//GEN-LAST:event_jComboFieldKeyPressed

    private void jTextYearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextYearKeyPressed
        int[] i ={37,39};
        JComponent[] j ={jComboField,jComboBatchNo};
        setCursor(i,j, evt);
    }//GEN-LAST:event_jTextYearKeyPressed

    private void jComboBatchNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBatchNoKeyPressed
        int[] i ={37,39};
        JComponent[] j ={jTextYear,jTextNumber};
        setCursor(i,j, evt);
    }//GEN-LAST:event_jComboBatchNoKeyPressed

    private void jTextNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNumberKeyPressed
        int[] i ={37,39,10};
        JComponent[] j ={jComboBatchNo,jBtnMarkDropout,jBtnMarkDropout};
        setCursor(i,j, evt);
    }//GEN-LAST:event_jTextNumberKeyPressed

    private void jBtnMarkDropoutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtnMarkDropoutKeyPressed
        try {
            getData();
        } catch (SQLException ex) {
            Logger.getLogger(MarkDropout.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MarkDropout.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnMarkDropoutKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarkDropout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarkDropout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarkDropout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarkDropout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MarkDropout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnDropout;
    private javax.swing.JButton jBtnMarkDropout;
    private javax.swing.JComboBox jComboBatchNo;
    private javax.swing.JComboBox jComboField;
    private javax.swing.JLabel jEstablishment1;
    private javax.swing.JLabel jIndexNo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextNumber;
    private javax.swing.JTextField jTextYear;
    // End of variables declaration//GEN-END:variables
}
